### What is Numpy?
1. Numpy is the fundamental package that enables numeric computing using        python.
2. It provides powerful ways to create, store, and/or manipulate data, which makes it easier to integerate with wide variety of databases.
3. It is a foundation that Pandas is built-on.
4. Pandas is another very important package that is used for data manipulation and data analysis.
5. With the help of numpy one can create array with certain data types, manipulate arrays, select elements from array, load datasets into array
 

In [2]:
# For starting, First we need to import a numpy library (abbr : 'np') using a 'import' keyword 
import numpy as np
import math

## Array Creation

In [5]:
# In python, Arrays are displayed as list or list of list which can be created through list as well.
# For creating arrays using numpy, we pass the list as a argument in numpy array.

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
# we can print the dimension of array using ndim attribute
print(a.ndim)
# Here, 1 reprsents array is of one-dimension

1


In [10]:
# We can also create multi-dimensional array , just need to pass list of list as a argument in numpy array
# for instance, a matrix
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.ndim)


[[1 2 3 4]
 [5 6 7 8]]
2


In [12]:
# We can also print the length of each dimension by calling 'shape' attribute, which return a tuple
b.shape
# Here, Tuple represents (row, column)

(2, 4)

In [13]:
# We can also check the data type of elemnts present in array by calling 'dtype' attribute
b.dtype
# Here, data present iside the array is of type integer and 32 represents the number of bits occupied by integer in the memory 

dtype('int32')

In [21]:
# Beside Integers, floats and other datatypes like String, charcters are also accepted in numpy arrays.
c = np.array([1,3,3.4, 5, "Hello"])
print(c)
print(c.dtype.name)

['1' '3' '3.4' '5' 'Hello']
str1024


In [28]:
# Suppose, we have an array of both float and integer elements in that situation
# the numpy automatically converts the integers into floats since, there is no loss of presision.
# Numpy will try to give you the best datatype format possible to keep your data homogenous
# which means, all the data is same in the array.
c1 = np.array([1.0,3,4.5])
print(c1)    

[1.  3.  4.5]


In [24]:
# Sometimes, there comes a situation where we know the shape of an array but, not what we want to be in it.
# Numpy provides two methods to thrive in this situation.
# Two methods : zero's and one's

d = np.zeros((2,3))
print(d)
# Here, zeros method create an array of given shape where every element is zero 
e = np.ones((2,3))
print(e)
# Just Like zeros method but only differnce exists is one instead of zero. 

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
# We can also generate an array with random numbers

f = np.random.rand(2,3)
print(f)

[[0.79688428 0.73514173 0.3322433 ]
 [0.16102124 0.29870747 0.37027045]]


In [39]:
# We can also create sequence of numbers in an array by calling 'arange()' methos.
# First argument is starting bound (inclusive), second argument is the ending bound(exclusive) and third bound is steps or differnce between each consecutive number.


# Lets create an array of every odd number from 1 (inclusive) to 50 (exclusive)

g = np.arange(1,50,2)
g


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [41]:
# if we want to generate a sequence of floats we can use linspace method.
# here, third argument is not difference between two consecutive numbers but,
# the total number of items you want inside of an array.

h = np.linspace(0,2, 10)
h

# 1o numbers form 0 (inclusive) to 10 (inclusive) 

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## Array Operations
